const cfg=window.AI_STUDIO_LAUNCH_CONFIG||{apiBase:"",maxSignals:6,room:"fall-2026-launch"};
const screens=[...document.querySelectorAll('.screen')];
const state={people:[],demoMode:false,connected:false,synthesis:null,pendingPhoto:''};
const storageKey=`ai-native-studio:${cfg.room}`,participantKey=`${storageKey}:participant-id`;
const $=id=>document.getElementById(id);
function show(id){screens.forEach(s=>s.classList.toggle('active',s.id===id));window.scrollTo({top:0,behavior:'instant'});}
function escapeHtml(value=''){return String(value).replace(/[&<>'\"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','\"':'&quot;'}[ch]));}
function participantId(){let id=localStorage.getItem(participantKey);if(!id){id=crypto.randomUUID();localStorage.setItem(participantKey,id);}return id;}
function loadLocal(){try{state.people=JSON.parse(localStorage.getItem(storageKey)||'[]');}catch{state.people=[];}}
function saveLocal(){try{localStorage.setItem(storageKey,JSON.stringify(state.people));}catch(error){console.warn('Local cache skipped',error);}}
function setConnection(mode){const el=$('connectionStatus');if(!el)return;el.className='status-pill';if(mode==='demo'){el.textContent='DEMO MODE';el.classList.add('demo');return;}if(mode==='online'){el.textContent='LIVE · CONNECTED';el.classList.add('online');return;}el.textContent='OFFLINE';el.classList.add('offline');}
function joinLink(){const url=new URL(window.location.href);url.search='';url.searchParams.set('join','1');url.searchParams.set('room',cfg.room);url.hash='';return url.toString();}
function rosterLink(){const url=new URL('roster.html',window.location.href);url.searchParams.set('room',cfg.room);return url.toString();}
function validateLinkedIn(value){const raw=String(value||'').trim();if(!raw)return'';let url;try{url=new URL(raw);}catch{throw new Error('Please enter a valid LinkedIn profile URL.');}const host=url.hostname.toLowerCase(),validHost=['linkedin.com','www.linkedin.com'].includes(host),validPath=url.pathname.toLowerCase().startsWith('/in/');if(url.protocol!=='https:'||!validHost||!validPath)throw new Error('Please use your public LinkedIn profile URL, such as https://www.linkedin.com/in/your-name');url.search='';url.hash='';return url.toString();}
async function syncRemote(){if(!cfg.apiBase||state.demoMode)return;try{const response=await fetch(`${cfg.apiBase}?room=${encodeURIComponent(cfg.room)}`,{cache:'no-store'});if(!response.ok)throw new Error('sync failed');const data=await response.json();state.connected=true;setConnection('online');if(Array.isArray(data.people)){state.people=data.people.slice(0,cfg.maxSignals);saveLocal();renderPeople();}}catch(error){state.connected=false;setConnection('offline');console.warn('Live sync unavailable',error);}}
async function submitSignal(person){state.demoMode=false;if(cfg.apiBase){const response=await fetch(`${cfg.apiBase}?room=${encodeURIComponent(cfg.room)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({room:cfg.room,person})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.reason==='room-full'?'The studio wall is full.':data.error||'Submission failed');state.connected=true;if(Array.isArray(data.people)){state.people=data.people.slice(0,cfg.maxSignals);saveLocal();renderPeople();}return;}const existingIndex=state.people.findIndex(p=>p.id===person.id);if(existingIndex>=0)state.people[existingIndex]=person;else if(state.people.length<cfg.maxSignals)state.people.push(person);saveLocal();renderPeople();}
function renderPeople(){const grid=$('peopleGrid');if(!grid)return;grid.innerHTML='';for(let index=0;index<cfg.maxSignals;index+=1){const person=state.people[index],card=document.createElement('article');card.className=`person-card ${person?'filled':''}`;const portrait=person?.photo?`<img class="person-portrait" src="${person.photo}" alt="Portrait of ${escapeHtml(person.name)}" />`:'';const linkedInMark=person?.linkedin?'<span class="person-linkedin" title="LinkedIn profile included">in</span>':'';const remove=person?`<button class="person-remove" type="button" data-person-id="${person.id}" data-person-name="${escapeHtml(person.name)}" aria-label="Remove ${escapeHtml(person.name)}">REMOVE</button>`:'';card.innerHTML=`${portrait}${remove}<div class="person-num">${String(index+1).padStart(2,'0')}</div><div class="person-name">${person?`${escapeHtml(person.name)} ${linkedInMark}`:'WAITING'}</div><div class="person-answer">${person?escapeHtml(person.answer):'Signal not received yet.'}</div>`;grid.appendChild(card);}const count=state.people.length;$('count').textContent=count;if($('createPosterBtn'))$('createPosterBtn').disabled=count===0;const ready=$('readinessStatus'),hint=$('posterHint');if(count===0){if(ready)ready.textContent='Waiting for the first signal.';if(hint)hint.textContent='Add at least one student to create the poster.';}else if(count<cfg.maxSignals){if(ready)ready.textContent=`${count} of ${cfg.maxSignals} signals received.`;if(hint)hint.textContent=`Poster ready with ${count}. Best result when all ${cfg.maxSignals} students are in.`;}else{if(ready)ready.textContent='All six signals received.';if(hint)hint.textContent='All six students are in. Create the poster.';}}
async function resizePortrait(file){if(!file||!file.type.startsWith('image/'))throw new Error('Please choose an image.');if(file.size>12*1024*1024)throw new Error('That photo is too large. Choose one under 12 MB.');const bitmap=await createImageBitmap(file),side=Math.min(bitmap.width,bitmap.height),sx=(bitmap.width-side)/2,sy=(bitmap.height-side)/2,canvas=document.createElement('canvas');canvas.width=420;canvas.height=420;canvas.getContext('2d').drawImage(bitmap,sx,sy,side,side,0,0,420,420);bitmap.close?.();return canvas.toDataURL('image/jpeg',0.68);}
function fallbackSynthesis(){const count=state.people.length;return{themes:['curiosity','experimentation','human-centered','useful'],signal:'CURIOUS × EXPERIMENTAL × HUMAN-CENTERED × USEFUL',mission:`We are ${count} students turning curiosity into useful AI products—experimenting boldly, building responsibly, and learning through real work.`,linkedin:`What happens when a classroom starts operating like an AI product studio?\n\nToday, ${count} students in NKU’s INF 396: AI Native Studio shared what they want to make possible with AI this semester.\n\nThose individual ambitions became our first studio signal.\n\nWe’re not studying AI. We’re building with it.\n\n6 humans. 2 clients. 1 AI studio.`,source:'fallback'};}
async function getSynthesis(){if(cfg.apiBase&&!state.demoMode){try{const response=await fetch(`${cfg.apiBase}/synthesize?room=${encodeURIComponent(cfg.room)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({room:cfg.room})});if(response.ok){const result=await response.json();if(result?.mission)return result;}}catch(error){console.warn('AI synthesis unavailable',error);}}return fallbackSynthesis();}
function renderPoster(){const people=state.people.slice(0,cfg.maxSignals),posterPeople=$('posterPeople');posterPeople.innerHTML='';posterPeople.dataset.count=String(people.length);people.forEach((person,index)=>{const item=document.createElement('article');item.className='poster-person-card';const photo=person.photo?`<img src="${person.photo}" alt="Portrait of ${escapeHtml(person.name)}" />`:`<div class="poster-initial">${escapeHtml(String(person.name||'?').charAt(0).toUpperCase())}</div>`;item.innerHTML=`<div class="poster-person-photo">${photo}<span class="poster-person-number">${String(index+1).padStart(2,'0')}</span></div><div class="poster-person-name">${escapeHtml(person.name)}</div>`;posterPeople.appendChild(item);});const synthesis=state.synthesis||fallbackSynthesis();$('posterSignal').textContent=synthesis.signal||synthesis.themes?.map(theme=>theme.toUpperCase()).join(' × ')||'CURIOUS × EXPERIMENTAL × HUMAN-CENTERED';$('posterMission').textContent=synthesis.mission;$('posterCount').textContent=people.length;const rosterUrl=rosterLink();$('rosterQr').src=`https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=${encodeURIComponent(rosterUrl)}`;}
async function createPoster(){if(!state.people.length)return;show('thinking');state.synthesis=await getSynthesis();renderPoster();await new Promise(resolve=>setTimeout(resolve,500));show('poster');}
async function copyCaption(){const synthesis=state.synthesis||fallbackSynthesis(),text=`${synthesis.linkedin}\n\nMeet the studio: ${rosterLink()}`;try{await navigator.clipboard.writeText(text);const button=$('copyCaptionBtn'),original=button.textContent;button.textContent='CAPTION COPIED';setTimeout(()=>button.textContent=original,1400);}catch{window.prompt('Copy your LinkedIn caption:',text);}}
function openRoster(){window.open(rosterLink(),'_blank','noopener');}
function loadDemo(){state.demoMode=true;state.synthesis=null;state.people=[{id:crypto.randomUUID(),name:'Aaron',answer:'Build intelligent agents that can make better decisions with people.',linkedin:'',photo:'',createdAt:new Date().toISOString()},{id:crypto.randomUUID(),name:'Ashok',answer:'Turn ambitious ideas into useful AI products people can trust.',linkedin:'',photo:'',createdAt:new Date().toISOString()},{id:crypto.randomUUID(),name:'Mark',answer:'Use computer vision to help people discover stories in museum collections.',linkedin:'',photo:'',createdAt:new Date().toISOString()},{id:crypto.randomUUID(),name:'Elaina',answer:'Create human-centered AI experiences that make information easier to explore.',linkedin:'',photo:'',createdAt:new Date().toISOString()},{id:crypto.randomUUID(),name:'Nora',answer:'Experiment boldly while keeping the technology responsible and useful.',linkedin:'',photo:'',createdAt:new Date().toISOString()},{id:crypto.randomUUID(),name:'Aaron',answer:'Learn how real AI teams move from uncertainty to working products.',linkedin:'',photo:'',createdAt:new Date().toISOString()}];saveLocal();renderPeople();setConnection('demo');}
$('hostBtn').addEventListener('click',()=>show('host'));$('joinBtn').addEventListener('click',()=>show('join'));document.querySelectorAll('[data-back]').forEach(button=>button.addEventListener('click',()=>show(button.dataset.back)));
$('photoInput').addEventListener('change',async event=>{const file=event.target.files?.[0];if(!file)return;try{state.pendingPhoto=await resizePortrait(file);$('portraitPreview').src=state.pendingPhoto;$('portraitPreviewWrap').classList.remove('hidden');$('photoPickerText').textContent='CHANGE PHOTO';}catch(error){alert(error.message||'Could not prepare that photo.');event.target.value='';}});
$('removePhotoBtn').addEventListener('click',()=>{state.pendingPhoto='';$('photoInput').value='';$('portraitPreviewWrap').classList.add('hidden');$('photoPickerText').textContent='TAKE OR CHOOSE PHOTO';});
$('joinForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,name=$('nameInput').value.trim(),answer=$('answerInput').value.trim();if(!name||!answer)return;let linkedin='';try{linkedin=validateLinkedIn($('linkedinInput').value);}catch(error){alert(error.message);return;}const person={id:participantId(),name,answer,linkedin,photo:state.pendingPhoto||'',createdAt:new Date().toISOString()};try{await submitSignal(person);form.classList.add('hidden');$('joinSuccess').classList.remove('hidden');$('studentRosterLink').href=rosterLink();}catch(error){alert(error?.message||'Your signal could not be submitted. Please try again.');}});
$('copyJoinBtn').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(joinLink());const button=$('copyJoinBtn'),original=button.textContent;button.textContent='COPIED';setTimeout(()=>button.textContent=original,1200);}catch{window.prompt('Copy this join link:',joinLink());}});
$('demoBtn').addEventListener('click',loadDemo);$('createPosterBtn').addEventListener('click',createPoster);$('copyCaptionBtn').addEventListener('click',copyCaption);$('openRosterBtn').addEventListener('click',openRoster);$('posterRosterBtn').addEventListener('click',openRoster);$('backToHostBtn').addEventListener('click',()=>show('host'));
window.addEventListener('storage',event=>{if(event.key===storageKey){loadLocal();renderPeople();}});
const joinUrl=joinLink();$('joinUrl').textContent=joinUrl;$('qrImage').src=`https://api.qrserver.com/v1/create-qr-code/?size=420x420&data=${encodeURIComponent(joinUrl)}`;$('studentRosterLink').href=rosterLink();const params=new URLSearchParams(window.location.search);if(params.get('join')==='1')show('join');loadLocal();renderPeople();syncRemote();setInterval(syncRemote,1000);