const cfg = window.AI_STUDIO_LAUNCH_CONFIG || { apiBase: "", maxSignals: 6, room: "fall-2026-launch" };
const screens=[...document.querySelectorAll('.screen')];
const state={people:[],lastScreen:'landing',demoMode:false,connected:false,synthesis:null,photoReturn:'reveal',pendingPhoto:''};
const storageKey=`ai-native-studio:${cfg.room}`;const participantKey=`${storageKey}:participant-id`;
function show(id){screens.forEach(s=>s.classList.toggle('active',s.id===id));state.lastScreen=id;window.scrollTo({top:0,behavior:'instant'});}
function openPhoto(returnTo='reveal'){state.photoReturn=returnTo;renderPortraitRoster();show('photo');}
function joinLink(){const url=new URL(window.location.href);url.search='?join=1';url.hash='';return url.toString();}
function participantId(){let id=localStorage.getItem(participantKey);if(!id){id=crypto.randomUUID();localStorage.setItem(participantKey,id);}return id;}
function loadLocal(){try{state.people=JSON.parse(localStorage.getItem(storageKey)||'[]');}catch{state.people=[];}}
function saveLocal(){try{localStorage.setItem(storageKey,JSON.stringify(state.people));}catch(e){console.warn('Local cache skipped',e);}}
function setConnection(mode){const el=document.getElementById('connectionStatus');if(!el)return;el.className='status-pill';if(mode==='demo'){el.textContent='DEMO MODE';el.classList.add('demo');}else if(mode==='online'){el.textContent='LIVE · CONNECTED';el.classList.add('online');}else{el.textContent='OFFLINE';el.classList.add('offline');}}
async function syncRemote(){if(!cfg.apiBase||state.demoMode)return;try{const r=await fetch(`${cfg.apiBase}?room=${encodeURIComponent(cfg.room)}`,{cache:'no-store'});if(!r.ok)throw new Error('sync failed');const data=await r.json();state.connected=true;setConnection('online');if(Array.isArray(data.people)){state.people=data.people.slice(0,cfg.maxSignals);saveLocal();renderPeople();}}catch(e){state.connected=false;setConnection('offline');console.warn('Live sync unavailable',e);}}
async function submitSignal(person){state.demoMode=false;if(cfg.apiBase){const r=await fetch(`${cfg.apiBase}?room=${encodeURIComponent(cfg.room)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({room:cfg.room,person})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.reason==='room-full'?'The studio wall is full.':data.error||'Submission failed');state.connected=true;if(Array.isArray(data.people)){state.people=data.people.slice(0,cfg.maxSignals);saveLocal();renderPeople();}return;}const existingIndex=state.people.findIndex(p=>p.id===person.id);if(existingIndex>=0)state.people[existingIndex]=person;else if(state.people.length<cfg.maxSignals)state.people.push(person);saveLocal();renderPeople();}
async function resetSignals(){state.demoMode=false;state.synthesis=null;if(!cfg.apiBase){state.people=[];saveLocal();renderPeople();return;}const token=window.prompt('Enter the host reset token.');if(!token)return;const r=await fetch(`${cfg.apiBase}?room=${encodeURIComponent(cfg.room)}`,{method:'DELETE',headers:{'X-Reset-Token':token}});if(!r.ok){alert('Reset failed. Check the host token.');return;}state.people=[];saveLocal();renderPeople();setConnection('online');}
function escapeHtml(str=''){return String(str).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[ch]));}
function renderPeople(){const grid=document.getElementById('peopleGrid');if(!grid)return;grid.innerHTML='';for(let i=0;i<cfg.maxSignals;i++){const p=state.people[i];const card=document.createElement('article');card.className=`person-card ${p?'filled':''}`;const portrait=p?.photo?`<img class="person-portrait" src="${p.photo}" alt="Portrait of ${escapeHtml(p.name)}" />`:'';card.innerHTML=`${portrait}<div class="person-num">0${i+1}</div><div class="person-name">${p?escapeHtml(p.name):'WAITING'}</div><div class="person-answer">${p?escapeHtml(p.answer):'Signal not received yet.'}</div>`;grid.appendChild(card);}const count=state.people.length;document.getElementById('count').textContent=count;document.getElementById('revealBtn').disabled=count===0;renderPortraitRoster();const ready=document.getElementById('readinessStatus'),hint=document.getElementById('readyHint');if(count===0){ready.textContent='Waiting for the first signal.';hint.textContent='The reveal unlocks after the first signal.';}else if(count<cfg.maxSignals){ready.textContent=`${count} of ${cfg.maxSignals} signals received.`;hint.textContent=`You can synthesize now, or wait for ${cfg.maxSignals-count} more.`;}else{ready.textContent='All six signals received. The studio is ready.';hint.textContent='All signals are in. Time for the reveal.';}}
function renderPortraitRoster(){const roster=document.getElementById('portraitRoster');if(!roster)return;roster.innerHTML='';const people=state.people.slice(0,cfg.maxSignals);roster.dataset.count=String(people.length);const sub=document.getElementById('photoSub');if(sub){const n=people.length||cfg.maxSignals;sub.textContent=`${n} ${n===1?'HUMAN':'HUMANS'} · 2 CLIENTS · 1 AI STUDIO`;}
  if(!people.length){const empty=document.createElement('div');empty.className='poster-empty';empty.innerHTML='<strong>THE STUDIO IS ASSEMBLING.</strong><span>Student portraits will appear here live.</span>';roster.appendChild(empty);return;}
  people.forEach((p,index)=>{const item=document.createElement('article');item.className=`poster-person ${p.photo?'has-photo':'no-photo'}`;const media=document.createElement('div');media.className='poster-media';if(p.photo){const img=document.createElement('img');img.src=p.photo;img.alt=`Portrait of ${p.name}`;media.appendChild(img);}else{const placeholder=document.createElement('div');placeholder.className='poster-placeholder';placeholder.textContent=String(p.name||'?').charAt(0).toUpperCase();media.appendChild(placeholder);}const badge=document.createElement('span');badge.className='poster-index';badge.textContent=String(index+1).padStart(2,'0');media.appendChild(badge);const label=document.createElement('div');label.className='poster-name';label.textContent=p.name||'STUDIO';item.append(media,label);roster.appendChild(item);});}
async function resizePortrait(file){if(!file||!file.type.startsWith('image/'))throw new Error('Please choose an image.');if(file.size>12*1024*1024)throw new Error('That photo is too large. Choose one under 12 MB.');const bitmap=await createImageBitmap(file);const side=Math.min(bitmap.width,bitmap.height);const sx=(bitmap.width-side)/2,sy=(bitmap.height-side)/2;const canvas=document.createElement('canvas');canvas.width=420;canvas.height=420;canvas.getContext('2d').drawImage(bitmap,sx,sy,side,side,0,0,420,420);bitmap.close?.();return canvas.toDataURL('image/jpeg',0.68);}
function fallbackSynthesis(){const answers=state.people.map(p=>p.answer.toLowerCase()).join(' ');const candidates=['curious','experimental','human','useful','bold','creative','responsible','inventive','practical','ambitious'];const hits=candidates.filter(w=>answers.includes(w));const themes=[...new Set([...hits,'curious','experimental','human-centered','useful'])].slice(0,4);const count=state.people.length;return{themes,signal:themes.map(x=>x.toUpperCase()).join(' × '),mission:`We are ${count} students turning curiosity into useful AI products—experimenting boldly, building responsibly, and learning through real work.`,prediction:'Six NKU students prove what happens when the classroom starts operating like an AI product studio.',linkedin:`I asked ${count} students one question: “What do you want to make possible with AI this semester?”\n\nTheir answers became the first signal for INF 396: AI Native Studio. We’re not studying AI. We’re building with it.\n\n6 humans. 2 clients. 1 AI studio.`,source:'fallback'};}
async function synthesizeStudio(){if(!state.people.length)return;show('thinking');const phrases=['Finding the patterns between what you want to build.','Looking for the ideas that connect this team.','Turning individual ambitions into a shared studio signal.'];let phraseIndex=0;const timer=setInterval(()=>{phraseIndex=(phraseIndex+1)%phrases.length;document.getElementById('thinkingCopy').textContent=phrases[phraseIndex];},1400);let result=null;try{if(cfg.apiBase&&!state.demoMode){const r=await fetch(`${cfg.apiBase}/synthesize?room=${encodeURIComponent(cfg.room)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({room:cfg.room})});if(r.ok)result=await r.json();}}catch(e){console.warn('AI synthesis unavailable',e);}if(!result?.mission)result=fallbackSynthesis();state.synthesis=result;clearInterval(timer);await new Promise(r=>setTimeout(r,700));applySynthesis(result);show('reveal');}
function applySynthesis(result){const themes=Array.isArray(result.themes)?result.themes.slice(0,5):[];const chips=document.getElementById('themeChips');chips.innerHTML='';themes.forEach(theme=>{const span=document.createElement('span');span.textContent=theme;chips.appendChild(span);});document.getElementById('signalLine').textContent=result.signal||themes.map(x=>x.toUpperCase()).join(' × ');document.getElementById('missionText').textContent=result.mission;document.getElementById('prediction-title').textContent=result.prediction||fallbackSynthesis().prediction;document.getElementById('photoMission').textContent=result.mission;document.getElementById('aiSource').textContent=result.source==='ai'?'Synthesized live with Cloudflare Workers AI from this room’s signals.':'Synthesized from this room’s signals with the classroom fallback.';}
async function copyLinkedIn(){const text=state.synthesis?.linkedin||fallbackSynthesis().linkedin;try{await navigator.clipboard.writeText(text);[document.getElementById('copyLinkedInBtn'),document.getElementById('predictionCopyBtn')].forEach(button=>{if(!button)return;const original=button.textContent;button.textContent='CAPTION COPIED';setTimeout(()=>button.textContent=original,1500);});}catch{window.prompt('Copy this LinkedIn caption:',text);}}
function loadDemo(){state.demoMode=true;state.synthesis=null;state.people=[{id:crypto.randomUUID(),name:'Aaron',answer:'Build intelligent agents that can make better decisions with people.'},{id:crypto.randomUUID(),name:'Ashok',answer:'Turn ambitious ideas into useful AI products people can trust.'},{id:crypto.randomUUID(),name:'Mark',answer:'Use computer vision to help people discover stories in museum collections.'},{id:crypto.randomUUID(),name:'Elaina',answer:'Create human-centered AI experiences that make information easier to explore.'},{id:crypto.randomUUID(),name:'Nora',answer:'Experiment boldly while keeping the technology responsible and useful.'},{id:crypto.randomUUID(),name:'Aaron',answer:'Learn how real AI teams move from uncertainty to working products.'}];saveLocal();renderPeople();setConnection('demo');}
document.getElementById('hostBtn').addEventListener('click',()=>show('host'));document.getElementById('joinBtn').addEventListener('click',()=>show('join'));document.querySelectorAll('[data-back]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.back)));
document.getElementById('photoInput').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{state.pendingPhoto=await resizePortrait(file);document.getElementById('portraitPreview').src=state.pendingPhoto;document.getElementById('portraitPreviewWrap').classList.remove('hidden');document.getElementById('photoPickerText').textContent='CHANGE PHOTO';}catch(error){alert(error.message||'Could not prepare that photo.');e.target.value='';}});
document.getElementById('removePhotoBtn').addEventListener('click',()=>{state.pendingPhoto='';document.getElementById('photoInput').value='';document.getElementById('portraitPreviewWrap').classList.add('hidden');document.getElementById('photoPickerText').textContent='TAKE OR CHOOSE PHOTO';});
document.getElementById('joinForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;const name=document.getElementById('nameInput').value.trim(),answer=document.getElementById('answerInput').value.trim();if(!name||!answer)return;try{await submitSignal({id:participantId(),name,answer,photo:state.pendingPhoto||'',createdAt:new Date().toISOString()});form.classList.add('hidden');document.getElementById('joinSuccess').classList.remove('hidden');}catch(error){alert(error?.message||'Your signal could not be submitted. Please try again.');}});
document.getElementById('copyJoinBtn').addEventListener('click',async()=>{await navigator.clipboard.writeText(joinLink());const b=document.getElementById('copyJoinBtn'),t=b.textContent;b.textContent='COPIED';setTimeout(()=>b.textContent=t,1200);});document.getElementById('demoBtn').addEventListener('click',loadDemo);document.getElementById('hostPhotoBtn').addEventListener('click',()=>openPhoto('host'));document.getElementById('resetBtn').addEventListener('click',resetSignals);document.getElementById('revealBtn').addEventListener('click',synthesizeStudio);document.getElementById('predictionBtn').addEventListener('click',()=>show('prediction'));document.getElementById('copyLinkedInBtn').addEventListener('click',copyLinkedIn);document.getElementById('predictionCopyBtn').addEventListener('click',copyLinkedIn);document.getElementById('photoBtn').addEventListener('click',()=>openPhoto('reveal'));document.getElementById('predictionPhotoBtn').addEventListener('click',()=>openPhoto('prediction'));document.getElementById('exitPhotoBtn').addEventListener('click',()=>show(state.photoReturn||'reveal'));window.addEventListener('storage',e=>{if(e.key===storageKey){loadLocal();renderPeople();}});
const url=joinLink();document.getElementById('joinUrl').textContent=url;document.getElementById('qrImage').src=`https://api.qrserver.com/v1/create-qr-code/?size=420x420&data=${encodeURIComponent(url)}`;const classDate=new Date(2026,7,25);document.getElementById('photoDate').textContent=`FIRST STUDIO SESSION · ${classDate.toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'}).toUpperCase()}`;loadLocal();renderPeople();if(new URLSearchParams(location.search).get('join')==='1')show('join');else show('landing');if(cfg.apiBase){syncRemote();setInterval(syncRemote,1000);}else setConnection('offline');
